ALTER TABLE "ride" ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE "ride" DROP CONSTRAINT IF EXISTS fk_ride_user;
ALTER TABLE "ride" ADD CONSTRAINT fk_ride_user FOREIGN KEY (user_id) REFERENCES users(id);
