spring.application.name=NL-14-backend
server.port=3000
server.forward-headers-strategy=native
spring.profiles.default=dev

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none

spring.cache.type=redis
spring.data.redis.host=redis-primary
spring.data.redis.port=6379
controller.logging.min-interval-ms=200
controller.logging.quantize-step=0.01
controller.logging.deadzone=0.05

springdoc.api-docs.path=/api-docs