spring.application.name=NL-14-backend
server.port=3000
server.forward-headers-strategy=native
spring.profiles.default=dev

spring.datasource.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none

spring.cache.type=simple
controller.logging.min-interval-ms=200
controller.logging.quantize-step=0.01
controller.logging.deadzone=0.05

springdoc.api-docs.path=/api-docs